# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zcm2UvOSlHF7xNM-ncQTeqQ-neB9HynU
"""

# задача 1
a = int(input())
if a % 2 == 0 :
  print("Данное число четное")
else :
    print("Данное число не является четным")

# задача 2
a = int(input())
b = int(input())
if a > b :
  print(a)
else :
  print(b)

# задача 3
a = int(input())
b = int(input())
if a % 2 == 0 and b % 2 != 0 :
  print("YES")
elif a % 2 != 0 and b % 2 == 0 :
    print("YES")
elif a % 2 == 0 and b % 2 == 0 :
    print("NO")
else :
    print("NO")