# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jw7zDyKJMsAWGgzk58DPlOiYZv-MpBpG
"""

# Задача 1
s = input()
A = s.split()
print(A[ : : -1])

# Задача 2
t = input()
print(t[ 0: : 2])

# Задача 3
s = input()
n = int(input())
A = s.split()
for i in range(len(A)):
    A[i] = int(A[i]) ** n
print(A)

# Задача 4
s = input("Строка : ")
sim = input("Символ : ")
a = s.replace(sim, sim * 2)
print(a)

# Задача 5
s = input()
x = input()
y = input()
a = s.count(x)
b = s.count(y)
print(x, ":", a,", ", y, ":", b)

# задача 6
s = input()
a = s.find("(")
b = s.find(")")
q = s[a + 1 : b]
print(q)
while True:
    a = s.find("(", b)
    b = s.find(")", a)
    if b == -1:
      break
    q = s[a + 1 : b]
    print(q)