# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ih7Kx8__26kETe-JQj_KlwDvuY2eCgxK
"""

# Задача 1
def uWu(q):
   q = q.lower()
   q = q.replace(" ", "")
   q = q.replace("-", "")
   q = q.replace(",", "")
   q = q.replace(".", "")
   q = q.replace("!", "")
   q = q.replace("?", "")
   w = q[::-1]
   if w == q:
     return True
   return False

b = input()
res = uWu(b)
print(res)

# Задача 2
def phio(q, w, e, r):
    a = " "
    r = str(2023 - r)
    return q + a + w + a + e + a + r + a + "г.р. зарегистрирован"

q = input("Фамилия : ")
w = input("Имя : ")
e = input("Отчество : ")
r = int(input("Возраст : "))
print(phio(q, w, e, r))

# Задача 3
def max(a, b, c = 0):
   if a > b and a > c:
     return a
   elif b > c and b > a :
     return b
   else:
     return c

print(max(1, 2, 6))