# -*- coding: utf-8 -*-
"""untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Pelmenyarosty/b16a8ec83bb3df26c860562988933f70/untitled12.ipynb
"""

# Задача 1
def uWu(q):
   w = q[::-1]
   if w == q:
     return True
   return False

b = input()
res = uWu(b)
print(res)

# Задача 2
def phio(q, w, e, r):
    a = " "
    return q + a + w + a + e + a + r + a + "г.р. зарегистрирован"

q = input("Фамилия : ")
w = input("Имя : ")
e = input("Отчество : ")
r = input("Год рожения : ")
print(phio(q, w, e, r))

# Задача 3
def max(a, b, c):
   if a > b and a > c:
     return a
   elif b > c and b > a :
     return b
   else:
     return c

q = int(input())
w = int(input())
e = int(input())
print(max(q, w, e))