# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wanVttZsJfSmkroZtwLOiVz3qOTSf_jK
"""

# Задача 1
a = ["dewuhg", 90, "fvuyeh6"]
b = [474, "hbdce", "vrr"]
a = list(map(str, a))
b = list(map(str, b))
d = list(map(lambda q, w : q + w, a, b))
d = "".join(d)
print(d)

# Задача 2
print("Числа писать через пробел")
w = input()
w = w.split()
w = map(int, w)
a = list(filter(lambda q : q % 19 == 0 or q % 13 == 0, w))
print(a)

# Задача 3
from functools import reduce
q = [13, 15, 2, 14]
x = reduce(max, q)
print(x)
