# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19JpF3cpuMFT_huJPlNnWYJZex5tIfDn8
"""

def findMax(x):
 if len(x) == 1:
   return x[0]
 else:
   a = findMax(x[1:])
   if x[0] > a:
     return x[0]
   else:
     return a

e = [1, 2, 3, 16]
s = findMax(e)
print(s)